import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { artScopeOptions, finishLevelOptions, rushLevelOptions, type ArtScope, type FinishLevel, type LicenseOption } from "@/lib/commission";
import { MultiplierRange, StudioSettings, normalizeStudioSettings } from "@/lib/studioSettings";
import { BookMarked, Info, LayoutList, Loader2, Plus, Save, SlidersHorizontal, X } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type Props = { settings: StudioSettings; loading: boolean; saving: boolean; error: string | null; onSave: (settings: StudioSettings) => Promise<void> };
const labels = { commercial: "商用", promotion: "宣傳", buyout: "買斷" } as const;
const money = (value: string) => { const n = Number(value); return value.trim() && n > 0 && Number.isFinite(n) ? n : null; };
const multiplier = (value: string, fallback: number) => { const n = Number(value); return n >= 1 && Number.isFinite(n) ? n : fallback; };

export default function StudioSettingsPage({ settings, loading, saving, error, onSave }: Props) {
  const [draft, setDraft] = useState(() => normalizeStudioSettings(settings)); const [scope, setScope] = useState<ArtScope>(artScopeOptions[0]); const [finish, setFinish] = useState<FinishLevel>(finishLevelOptions[0]); const [newPrice, setNewPrice] = useState("");
  useEffect(() => setDraft(normalizeStudioSettings(settings)), [settings]);
  const setPrice = (s: string, f: string, raw: string) => setDraft((d) => ({ ...d, combinationPrices: { ...d.combinationPrices, [s]: { ...d.combinationPrices[s], [f]: money(raw) } } }));
  const enabled = artScopeOptions.flatMap((s) => finishLevelOptions.flatMap((f) => { const p = draft.combinationPrices[s]?.[f] ?? null; return p === null ? [] : [{ s, f, p }]; }));
  const available = finishLevelOptions.filter((f) => draft.combinationPrices[scope]?.[f] === null);
  const range = (group: "rush" | "license", key: string, field: keyof MultiplierRange, value: string) => setDraft((d) => { const old = group === "rush" ? d.rushMultiplierRanges[key] ?? { min: 1, max: 1 } : d.licenseMultiplierRanges[key as LicenseOption] ?? { min: 1, max: 1 }; const next = { ...old, [field]: multiplier(value, old[field]) }; const valueRange = { min: Math.min(next.min, next.max), max: Math.max(next.min, next.max) }; return group === "rush" ? { ...d, rushMultiplierRanges: { ...d.rushMultiplierRanges, [key]: valueRange } } : { ...d, licenseMultiplierRanges: { ...d.licenseMultiplierRanges, [key]: valueRange } }; });
  const save = async () => { try { await onSave({ ...draft, updatedAt: Date.now() }); toast.success("丹青設案已儲存"); } catch { toast.error("儲存設定失敗，請檢查 Firebase 規則。"); } };
  if (loading) return <div className="flex min-h-[calc(100vh-70px)] items-center justify-center bg-[#fffdfa] text-sm text-[#456153]"><Loader2 className="mr-2 h-4 w-4 animate-spin" />正在展讀畫案設定…</div>;
  return <main className="min-h-[calc(100vh-70px)] bg-[#fffdfa] px-4 py-5 sm:px-7 sm:py-7"><div className="space-y-7"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-display text-3xl font-semibold text-[#283b31]">丹青設案</p><p className="mt-2 text-sm text-[#456153]">先設下可承接的畫法與倍率；寫畫起約只會開放已填定底價的組合。</p></div><Button className="bg-[#355b48] text-[#fffdfa] hover:bg-[#294a3a]" onClick={() => void save()} disabled={saving}>{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}{saving ? "落印中…" : "儲存設案"}</Button></header>{error && <p className="rounded-xl border border-[#bc694c] bg-[#fff0e9] p-3 text-sm text-[#8e4932]">Firebase 設定同步提示：{error}</p>}<Panel icon={<BookMarked />} title="畫案題名" description="此名稱會顯示在左側畫案標記中。"><Input value={draft.studioName} onChange={(e) => setDraft((d) => ({ ...d, studioName: e.target.value }))} placeholder="例如 繪月錄" /></Panel><Panel icon={<LayoutList />} title="組合底價" description="僅列出已啟用組合；停用價格後不再出現在寫畫起約。"><div className="rounded-xl border border-[#cfd9cf]">{enabled.map(({ s, f, p }) => <div key={`${s}-${f}`} className="grid gap-3 border-b border-[#e4ebe4] p-3 sm:grid-cols-[1fr_1fr_160px_auto]"><span>{s}</span><span>{f}</span><Input type="number" value={p} onChange={(e) => setPrice(s, f, e.target.value)} /><Button variant="ghost" size="icon" className="text-[#a9573c]" onClick={() => setPrice(s, f, "")}><X className="h-4 w-4" /></Button></div>)}</div><div className="mt-4 grid gap-3 rounded-xl border border-dashed border-[#b9cdbd] bg-[#edf5ed] p-4 lg:grid-cols-4"><Select value={scope} onValueChange={(v) => setScope(v as ArtScope)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{artScopeOptions.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Select value={available.includes(finish) ? finish : undefined} onValueChange={(v) => setFinish(v as FinishLevel)}><SelectTrigger><SelectValue placeholder="精緻度" /></SelectTrigger><SelectContent>{available.map((f) => <SelectItem key={f} value={f}>{f}</SelectItem>)}</SelectContent></Select><Input type="number" value={newPrice} onChange={(e) => setNewPrice(e.target.value)} placeholder="底價" /><Button className="bg-[#355b48] text-[#fffdfa]" onClick={() => { if (newPrice && available.includes(finish)) { setPrice(scope, finish, newPrice); setNewPrice(""); } }}><Plus className="mr-1 h-4 w-4" />啟用組合</Button></div></Panel><div className="grid gap-6 xl:grid-cols-2"><RangePanel title="加急倍率" entries={rushLevelOptions.map((x) => [x, x])} values={draft.rushMultiplierRanges} onChange={(k, f, v) => range("rush", k, f, v)} /><RangePanel title="權利倍率" entries={Object.entries(labels)} values={draft.licenseMultiplierRanges} onChange={(k, f, v) => range("license", k, f, v)} /></div></div></main>;
}
function Panel({ icon, title, description, children }: { icon: React.ReactNode; title: string; description: string; children: React.ReactNode }) { return <section className="rounded-[1.5rem] border border-[#cfd9cf] bg-[#fffdfa] p-5 shadow-[0_10px_35px_rgba(40,59,49,.06)]"><div className="flex gap-3"><span className="rounded-xl bg-[#dce9dc] p-2 text-[#355b48]">{icon}</span><div><h2 className="font-display text-2xl text-[#283b31]">{title}</h2><p className="text-sm text-[#456153]">{description}</p></div></div><div className="mt-4">{children}</div></section>; }
function RangePanel({ title, entries, values, onChange }: { title: string; entries: readonly (readonly [string, string])[]; values: Record<string, MultiplierRange>; onChange: (k: string, f: keyof MultiplierRange, v: string) => void }) { return <Panel icon={<SlidersHorizontal />} title={title} description="設定最小與最大倍率；委託單以最小值為預設。">{entries.map(([key, label]) => { const r = values[key] ?? { min: 1, max: 1 }; return <div className="mt-3 grid gap-3 rounded-xl bg-[#edf5ed] p-3 sm:grid-cols-3" key={key}><span>{label}</span><Input type="number" step="0.1" value={r.min} onChange={(e) => onChange(key, "min", e.target.value)} /><Input type="number" step="0.1" value={r.max} onChange={(e) => onChange(key, "max", e.target.value)} /></div>; })}</Panel>; }
